export class Types {
    static SET_AUTHENTICATED = "SET_AUTHENTICATED";
    static SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
    static SET_USER = "SET_USER";
    static SET_PROFILE = "SET_PROFILE";
    static SET_IMAGE_PROFILE = "SET_IMAGE_PROFILE";
    /*Screams*/
    static SET_SCREAMS = "SET_SCREAMS";
    static UNSET_SCREAMS = "UNSET_SCREAMS";
    static ADD_SCREAM = "ADD_SCREAM";
    static DELETE_SCREAM = "DELETE_SCREAM";
    /* Modal Scream*/
    static SHOW_MODAL_SCREAM = "SHOW_MODAL_SCREAM";
    static HIDE_MODAL_SCREAM = "HIDE_MODAL_SCREAM";
    static SET_SCREAM_MODAL = "SET_SCREAM_MODAL";
    static SET_LOADING_MODAL_SCREAM = "SET_LOADING_MODAL_SCREAM";
    static SET_COMMENT = "SET_COMMENT";
}
