export class Types {
    static SET_AUTHENTICATED = "SET_AUTHENTICATED";
    static SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
    static SET_USER = "SET_USER";
    static SET_PROFILE = "SET_PROFILE";
    static SET_IMAGE_PROFILE = "SET_IMAGE_PROFILE";
    /*Screams*/
    static SET_SCREAMS = "SET_SCREAMS";
    static UNSET_SCREAMS = "UNSET_SCREAMS";
    static ADD_SCREAM = "ADD_SCREAM";
    static DELETE_SCREAM = "DELETE_SCREAM";
}
